baseURL = 'https://ooransoy.github.io/'
languageCode = 'en-us'
title = "ooransoy's blog"
theme = 'risotto'
paginate = 3
copyright = "© 2024 Olcay Oransoy."
sectionPagesMenu = "main"

buildDrafts = true

[params]
noindex = false

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[params.about]
  title = "Hi, I'm [o̞ɫ'd͡ʒɑj.o̞'ɾɑnso̞j]."
  description = """
  IPA transcription courtesy of usuyus.

  CS @ Sabancı '26.
  """
  #logo = "⚡️"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
